<template>
    <div class="max-w-7xl mx-auto">
        hello, Go to
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <NuxtLink to="/test">Test Page</NuxtLink> 
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        or <NuxtLink to="/test2">Test Page 2</NuxtLink>
    </div> 
</template>
<script setup lang="ts">
    useSeoMeta({
        title: 'SSLTrust',
        description: 'ssltrust home page description',
    })
</script>